export const cadastroLocators = {
    radioGenero: 'input[type=radio]',
    inputSenha: 'input#password',
    selectDia: 'select[data-qa="days"]',
    selectMes: 'select[data-qa="months"]',
    selectAno: '[data-qa="years"]',
    checkboxNewsletter: 'input[type=checkbox]#newsletter',
    checkboxOptin: 'input[type=checkbox]#optin',
    inputPrimeiroNome: 'input#first_name',
    inputSobrenome: 'input#last_name',
    inputCompanhia: 'input#company',
    inputEndereco: 'input#address1',
    selectPais: 'select#country',
    inputEstado: 'input#state',
    inputCidade: 'input#city',
    inputCep: '[data-qa="zipcode"]',
    inputTelefone: '[data-qa="mobile_number"]',
    botaoCriarConta: 'button[data-qa="create-account"]',
    secaoAssinatura: '.single-widget',
    inputEmailAssinatura: '#susbscribe_email',
    botaoAssinar: '#subscribe',
    mensagemSucessoAssinatura: '.alert-success',
    mensagemContaCriada: 'h2[data-qa="account-created"]',
    mensagemContaErro: '.signup-form > form > p',
    mensagemContaExcluida: '.container',
    botaoContinuar: '[data-qa="continue-button"]'
};
